package org.example.session;

public enum SessionKey {
    RESPONSE,
    JSON_STRING,
    STATUS_CODE,
    DASHBOARD_NAME,
    WIDGET_NAME,
    DASHBOARD_ID,
    DASHBOARD_DESCRIPTION,
    DASHBOARD_INITIAL_NAME,
    EXPECTED_DASHBOARD_SIZE,
    SCENARIO_NAME
}
